# Generated by Django 5.0 on 2023-12-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
