# Generated by Django 5.0 on 2023-12-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_category_categorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='categorymodel',
            name='price',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='creat_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
